
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 13 11:14:53 COT 2015
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Consonante = 2;
  public static final int error = 1;
  public static final int OperadorS = 4;
  public static final int Vocal = 3;
  public static final int OperadorP = 5;
  public static final int FinSentencia = 6;
  public static final int EOF = 0;
}

